### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by Cerbo-xx** [Jonathan57500/aion-database-2.7#1]
Hi! 

Thanks for ur work! It's working correctly, when someone know how to "install"... :)
My question is, where is the SQL data? i migrated with artisan and its done created the vhost for the public dir..., but i not saw any items. :(

Have u data for Client_items table? 

Thanks Cerbo!

**Comment by Jonathan57500** [comment]
Hello,
This project doesn't seems to interest anybody, I didn't make new commit for a long time because no one needs it :)
Yes the item database is very strong, I have to find a way to upload it on Github

**Comment by Cerbo-xx** [comment]
That was a good news! 
Thanks! :)

**Comment by Cerbo-xx** [comment]
Have you ever found a solution to the data? maybe you can put it in some cloud.

**Comment by Jonathan57500** [comment]
Hi, sorry I was missing these last 3 weeks.
I didn't find a correct solution to include this data yet, I'm still trying to find a good way.
I don't want these data to be stored out of this depot.
Please note I only have 2.7 items EN and FR at this moment

**Comment by Cerbo-xx** [comment]
Hi!
 Nothing probelm! :D So... I/we need the 2.7 EN database... if you have solutions, do not keep yourself. :D

**Comment by swasun** [comment]
@Jonathan57500 Have you consider git lfs (https://git-lfs.github.com/) ? It's what I am using for large binary data.

**Comment by Jonathan57500** [comment]
Data have been integrated into the new version of this database
